# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    validator_service:
        class: AppBundle\Service\ValidatorService
        arguments: []

    chat_service:
        class: AppBundle\Service\ChatService
        arguments: [@doctrine.orm.entity_manager, @validator_service]
